name: CI

on:
  pull_request:
    types: [ opened, synchronize ]
  push:

jobs:
  do-various-checks:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Format Rust code
        env:
          TERM: xterm-256color # Make output colored. Only works on step, not on job.
        run: cargo fmt --all --check -- --color always
      
      - name: Clippy
        env:
          TERM: xterm-256color
        run: cargo clippy --workspace --all-targets --all-features --color always -- -D warnings

      - name: Unit tests
        run: cargo test --workspace --exclude benchmarks --color always
