name: CI

on:
  pull_request:
    types: [ opened, synchronize ]
  push:

jobs:
  do-various-checks:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Format Rust code
        env:
          TERM: xterm-256color # Make output colored. Only works on step, not on job.
        run: cargo fmt --all --check -- --color always
      
      - name: Clippy
        env:
          TERM: xterm-256color
        run: cargo clippy --workspace --all-targets --all-features --color always -- -D warnings

      - name: Unit tests
        run: cargo test --workspace --exclude benchmarks --color always

      - name: Install cbindgen
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install cbindgen

      - name: Run cbindgen
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cbindgen --config crates/wildbg-c/cbindgen.toml --crate wildbg-c --output crates/wildbg-c/wildbg.h --lang c

      - name: Check for changes in C API
        run: |
          if [[ -n $(git diff -- crates/wildbg-c/wildbg.h) ]]; then
            echo "::error file=crates/wildbg-c/wildbg.h::cbindgen output is outdated. Please run cbindgen and commit the result."
            git diff
            exit 1
          fi
